In [9]:
# Importando bibliotecas essenciais para ciência de dados
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns


# Livro Guia do Python para Data Science  
- **Título:** Python Data Science Handbook (Guia do Python para Data Science)  
- **Autor:** Jake VanderPlas  
- **Data:** 2024  
- **Versão:** 1.0  
- **Link:** [Amazon](https://www.amazon.com.br/Guia-Python-Para-Data-Science/dp/8550821713?&linkCode=ll1&tag=portaldosdado-20&linkId=8e923391a1281bb8d8fe31e3502f5aeb&language=pt_BR&ref_=as_li_ss_tl)

## Parte I - Jpupyter: Além do Python Comum

### Capítulo 01 - Começando com IPython e Jupyter

> **Neste Capítulo tem vários exemplos básicos de como consultar informações do seu código dentro do próprio Jupyter**

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [11]:
# Acessando a documentação de uma função
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [12]:
# Acessando a documentação de uma função usando ?
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [13]:
# Exemplo com listas e o método insert
L = [1, 2, 3, 4, 5]
L.insert?

Signature: L.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method

In [14]:
# Consultando a documentação
L?

Type:        list
String form: [1, 2, 3, 4, 5]
Length:      5
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [15]:
# Definindo uma função com docstring e acessando sua documentação
def square(x):
    """Returns the square of a number."""
    return x * x

square?

Signature: square(x)
Docstring: Returns the square of a number.
File:      c:\users\dione\appdata\local\temp\ipykernel_73076\777408048.py
Type:      function

In [16]:
# Interagindo com o Shell do Jupyter Notebook

!dir

 O volume na unidade C � Acer
 O N�mero de S�rie do Volume � 0EBD-0CFE

 Pasta de c:\Users\dione\Documents\GitHub\guia_do_python_para_data_science\01_Introducao_Python

07/12/2025  13:04    <DIR>          .
29/11/2025  10:54    <DIR>          ..
29/11/2025  10:53                 0 .gitkeep
07/12/2025  13:48             6.754 main.ipynb
               2 arquivo(s)          6.754 bytes
               2 pasta(s)   371.443.974.144 bytes dispon�veis


### Capítulo 02 - Recursos Interativos Aprimorados

> Não consegui identificar nada de útil nesse capítulo para mim, talvez para você ele possa ser.

### Capítulo 03 - Depuração e Perfil

> Não consegui identificar nada de útil nesse capítulo para mim, talvez para você ele possa ser.

## Parte II - Introdução ao NumPy

In [ ]:
# Verificando a versão do NumPy
np.__version__

'2.3.5'

In [ ]:
# Criando uma tupla usando um loop

result = ()
for n in range(10):
    result += (n,)
print(result)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


In [34]:
# Criando um array NumPy
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
# Arredondando valores em um array NumPy
np.array([1, 2, 3, 3.14]).round(2)


array([1.  , 2.  , 3.  , 3.14])

In [42]:
np.array([1, 2, 3, 3.5, 4.6], dtype=np.int64)

array([1, 2, 3, 3, 4])

In [44]:
# Criando um gerador de números aleatórios com semente fixa

rng = np.random.default_rng(seed=1701) # seed para reprodutibilidade

x1 = rng.integers(10, size=6) # 6 inteiros aleatórios entre 0 e 9, array unidimensional
x2 = rng.integers(10, size=(3, 4)) # array bidimensional 3x4
x3 = rng.integers(10, size=(3, 4, 5)) # array tridimensional 3x4x5

In [ ]:
# Exibindo as propriedades do array x3

print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)
print('x3 dtype:', x3.dtype)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int64


In [51]:
!head -4 data/president_heights.csv


'head' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.


In [52]:
pd.read_csv('data/president_heights.csv').head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/president_heights.csv'